server:
  port: 8001


eureka:
  instance:
    hostname: localhost # 主机名
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      # eureka服务端地址，将来客户端使用该地址和eureka进行通信
    register-with-eureka: true
    # 是否将自己的路径注册到eureka上。eureka server不需要的，eureka provider client需要。
    # 一般服务提供方需要向eureka server注册自己的路径，服务消费方不需要
    fetch-registry: true
    # 是否需要从eureka中抓取路径。eureka server不需要的，eureka consumer client需要
    # 服务消费方需要抓取路径。一个服务可能既是服务提供方又是消费方

spring:
  application:
    name: eureka-provider # 设置当前应用的名称。将来会在eureka中Application显示。将来需要使用该名称来获取路径。不设置的话在eureka服务控制台显示UNKOWN
