# eureka-server默认的端口就是8761
server:
  port: 8761

# eureka 配置
# eureka 一共有4部分 配置
# 1. dashboard:eureka的web控制台配置
# 2. server:eureka的服务端配置
# 3. client:eureka的客户端配置
# 4. instance:eureka的实例配置


eureka:
  instance:
    hostname: localhost # 主机名
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      # eureka服务端地址，将来客户端使用该地址和eureka进行通信

    register-with-eureka: false
    # 是否将自己的路径注册到eureka上。eureka server不需要的，eureka provider client需要。
    # 一般服务提供方需要向eureka server注册自己的路径，服务消费方不需要
    fetch-registry: false
    # 是否需要从eureka中抓取路径。eureka server不需要的，eureka consumer client需要
    # 服务消费方需要抓取路径
